# Railway Configuration for OpenVINO Support
[build]
  builder = "nixpacks"

[deploy]
  startCommand = "python app.py"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  FLASK_ENV = "production"
  AI_DEMO_MODE = "false"
  PORT = "5000"
